### ISSUE TITLE
Reap across namespaces

### ISSUE THREAD

**Issue by atombender** [sstarcher/job-reaper#5]
It's unclear to me whether this only looks for jobs in the current namespace (it appears so?). If so, an option such as `--all-namespaces` should be added, so that it can be installed once, into a namespace such as `kube-system`, and operate on jobs across all namespaces.

**Comment by jmccarty3** [comment]
@atombender the reaper does actually work across all namespaces. It first iterates across all namespaces prior to working through each one by one. https://github.com/sstarcher/job-reaper/blob/e8cf242ac8f3bf8dcf2bd7d5c973d673d114a733/kube/kube.go#L210

**Comment by atombender** [comment]
Oops, I missed that line of code. Excellent, thanks!
